name: Flask app tests
on:
  push:
    branches:
      - flask-wsgi-2.2.3
  pull_request:
    branches:
      - flask-wsgi-2.2.3
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip modules
        id: cache-pip-modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        if: steps.cache-pip-modules.outputs.cache-hit != 'true'
        working-directory: ./wsgi_app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flask app
        working-directory: ./wsgi_app
        run: |
          python wsgi.py
